### PR TITLE
Decommission kit services VM

### PR DESCRIPTION
**Pull request by RealOrangeOne**
This will return for the competition

## Summary

:ronseal:

### Testing

- [ ] applied the configuration locally
- [ ] manually validated the new behaviour
- [x] ... is for chumps

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
@RealOrangeOne as noted elsewhere, please can you test this.

**Comment by RealOrangeOne** [comment]
```
$ ./scripts/apply --limit kitsvcs     
[WARNING]: Could not match supplied host pattern, ignoring: kitsvcs
ERROR! Specified inventory, host pattern and/or --limit leaves us with no hosts to target.
```
Yep, that works.

**Review by PeterJCLaw — APPROVED** [review]
Just to check -- is it intentional that the vagrant config remain in place here? That is: are we expecting that we will want the kit services stuff back sometime soon?

**Comment by RealOrangeOne** [comment]
The physical server was decommissioned to save costs and maintenance. 

> This will return for the competition

**Comment by PeterJCLaw** [comment]
> The physical server was decommissioned to save costs and maintenance.
> 
> > This will return for the competition

:facepalm: sorry, apparently I'm failing to read this evening.

**Pull request merged**
