### PR TITLE
Add redirect to tasks project

### PR DESCRIPTION
**Pull request by RealOrangeOne**
## Summary

:ronseal:

### Testing

- [ ] applied the configuration locally
- [ ] manually validated the new behaviour
- [x] _YOLO_

### Links

Requested in https://studentrobotics.slack.com/archives/C02BXUAK33M/p1723664801500719

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
@RealOrangeOne please can you test this? I appreciate that this change is low risk, however I would prefer that we get into a habit of testing changes rather than YOLOing them.

**Review by WillB97 — APPROVED** [review]

**Comment by PeterJCLaw** [comment]
This needs testing. The procedure for doing so is fairly simple -- run the VM locally (see instructions in the README) and verify that the redirect works as intended as well as that the rest of the setup is still working (checking that the homepage still loads is fine).

I don't mind testing the occasional PR which others submit and don't have time to check, however I don't think it's fair that reviewers are asked to take on the testing of _all_ submissions as seems to be happening at the moment. I have requested that @RealOrangeOne test this and other PRs in the past, without response, and would prefer not to let the expectation become that I end up doing all the testing.

**Comment by WillB97** [comment]
This is very much an infrastructure team issue and the timescales that have elapsed here are much longer than what is suggested by the [Infrastructure Operations](https://studentrobotics.org/runbook/infrastructure/operations/) page.

**Comment by PeterJCLaw** [comment]
The infrastructure portion of this is the provision of the proxy. The content of the proxy, specifically adding custom redirects is IMO not infrastructure (though the team are almost certainly responsible for reviewing and applying the changes).

The request that the PR be tested before it is put up for review would apply to all submitters, regardless of their originating team.

The responses to the PR have been well within the timeframes indicated in the runbook as desirable. Even if we agreed about where this PR sits relative to the team boundaries (which I suspect we don't), I would still push for proper testing of this change before it were pushed live - regardless of any documented timescale objective.

While the author of this PR has historically been a member of the infrastructure team, they have not attended meetings in over 6 months. I'm not aware of any formal policy around what timeframe membership of a team lapses, though I think it would be unfair to claim that they were acting purely as a member of the infrastructure team in this case given that history.

I therefore reject the suggestion that this is purely an infrastructure team matter and the implication that the timescales suggested in the runbook be used to subvert due process.

**Comment by RealOrangeOne** [comment]
This PR was opened as a volunteer who knows Ansible, making an incredibly simple change to help a fellow volunteer. It shouldn't matter what team(s) I represent, when opening this PR or otherwise.

> While the author of this PR has historically been a member of the infrastructure team, they have not attended meetings in over 6 months.

For a number of well-known personal reasons. However, with attitudes like this, is there any wonder? I'm also _fairly_ sure my absence doesn't strip me of a name?

---

There's **plenty** more I have to say about the comments on this PR, and how they're a prime example of volunteer de-motivation and unnecessary conflict. But, quite honestly, I have neither the time, patience nor energy to write them, let alone read whatever someone may deem a valid response to them.

---

```
$ curl https://sr-proxy/tasks -ksI | grep location
location: https://github.com/orgs/srobo/projects/24/
```

**Review by PeterJCLaw — APPROVED** [review]

**Comment by PeterJCLaw** [comment]
Thank you for testing this.

**Pull request merged**
